spring:
  datasource:
    application:
      url: ${PARKING_LOT_APP_DB_JDBC_URL}
      username: ${PARKING_LOT_APP_DB_USERNAME}
      password: ${PARKING_LOT_APP_DB_PASSWORD}
      driverClassName: ${PARKING_LOT_APP_DB_DRIVER}
    auth:
      url: ${PARKING_LOT_AUTH_DB_JDBC_URL}
      username: ${PARKING_LOT_AUTH_DB_USERNAME}
      password: ${PARKING_LOT_AUTH_DB_PASSWORD}
      driverClassName: ${PARKING_LOT_AUTH_DB_DRIVER}
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    properties:
      hibernate:
        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        generate_statistics: ${PARKING_LOT_HBR_GENERATE_STATISTICS:true}
        jdbc:
          batch_size: ${PARKING_LOT_HBR_BATCH_SIZE:20}
        order_inserts: ${PARKING_LOT_HBR_ORDER_INSERTS:true}
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

logging:
  level:
    org:
      springframework:
        orm:
          jpa:
            JpaTransactionManager: ${PARKING_LOT_LOG_LEVEL_JPA_TXN_MANAGER:ERROR}
      hibernate:
        SQL: ${PARKING_LOT_LOG_LEVEL_HBR_SQL:DEBUG}
        type:
          descriptor:
            sql:
              BasicBinder: ${PARKING_LOT_LOG_LEVEL_HBR_STMT_PREPARED:TRACE}

slot:
  booking:
    strategy: lowestOnAllFromDb

pagination:
  slot:
    size: 5

jwt:
  secret: ${PARKING_LOT_JWT_SECRET}