spring:
  datasource:
    application:
      url: jdbc:postgresql://localhost:5432/automated_parking_lot
      username: postgres
      driverClassName: org.postgresql.Driver
    auth:
      url: jdbc:postgresql://localhost:5432/auth_service
      username: postgres
      driverClassName: org.postgresql.Driver
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    properties:
      hibernate:
        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        generate_statistics: ${PARKING_LOT_HBR_GENERATE_STATISTICS:true}
        jdbc:
          batch_size: ${PARKING_LOT_HBR_BATCH_SIZE:20}
        order_inserts: ${PARKING_LOT_HBR_ORDER_INSERTS:true}
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

logging:
  level:
    org:
      springframework:
        orm:
          jpa:
            JpaTransactionManager: ${PARKING_LOT_LOG_LEVEL_JPA_TXN_MANAGER:ERROR}
      hibernate:
        SQL: ${PARKING_LOT_LOG_LEVEL_HBR_SQL:DEBUG}
        type:
          descriptor:
            sql:
              BasicBinder: ${PARKING_LOT_LOG_LEVEL_HBR_STMT_PREPARED:TRACE}

slot:
  booking:
    strategy: lowestOnAllFromDb

pagination:
  slot:
    size: 5