spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/automated_parking_lot
    username: postgres
  jackson:
    property-naming-strategy: SNAKE_CASE

slot:
  booking:
    strategy: lowestOnAllFromDb